//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public int BransID { get; set; }
        public int DoktorID { get; set; }
        public System.DateTime RandevuZamani { get; set; }
    
        public virtual Bran Bran { get; set; }
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
